export const FULL_SCREEN_BREAKPOINT = 1000;
export const TABLET_SCREEN_BREAKPOINT = 500;
export const MOBILE_SCREEN_BREAKPOINT = 0;

export const FULL_SCREEN_QUANTITY_MOVIES = 12;
export const TABLET_SCREEN_QUANTITY_MOVIES = 8;
export const MOBILE_SCREEN_QUANTITY_MOVIES = 5;
export const INITIAL_STATE_QUANTITY_MOVIES = 0;

export const FULL_SCREEN_MORE_BUTTON = 3;
export const TABLET_SCREEN_MORE_BUTTON = 2;

export const QUANTITY_MINUTES_IN_HOUR = 60;

export const SHORT_MOVIE_DURATION = 40;




